require([
	"dojo/ready", 
	"dojo/parser",
	"dijit/layout/BorderContainer",
"dijit/_KeyNavContainer",
"dijit/layout/AccordionPane",
"dojo/selector/acme",
"dojo/_firebug/firebug",
"dojo/selector/lite",
"dojo/store/Memory",
"dojo/data/ObjectStore",
"dojo/store/util/QueryResults",
"dojo/store/util/SimpleQueryEngine",
	"rmcwidget/AccordionContainerEx",
	"rmcwidget/DojoTreePane",
	"rmcwidget/IFrameContentPane",	
	"rmcwidget/BannerWidget"
]);